spring.application.name=mapero

spring.datasource.url=jdbc:postgresql://ep-young-star-ac7jppz9-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_PF4qJnRomgi2
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
